name: batchcp
channels:
  - bioconda
  - conda-forge
dependencies:
  - tensorflow=2.11.1
  - cudatoolkit=11.2.2
  - anndata2ri=1.1
  - anndata=0.10.3
  - chex=0.1.6
  - deprecated=1.2.14
  - leidenalg=0.9.1
  - llvmlite=0.41.1
  - louvain=0.8.0
  - numba=0.58.1
  - numpy=1.24.4
  - pandas=1.5.3
  - pillow=10.0.1
  - pip=23.3.1
  - plotly=5.18.0
  - plottable=0.1.5
  - pyarrow=11.0.0
  - pydot=1.2.4
  - pymde=0.1.18
  - pynndescent=0.5.11
  - python-kaleido=0.2.1
  - r-remotes=2.4.2.1
  - r-matrixstats=1.1.0
  - r-arrow=11.0.0
  - bioconductor-batchelor=1.14.0
  - rpy2=3.5.11
  - scanpy=1.9.5
  - scikit-learn=1.3.2
  - scikit-misc=0.1.4
  - scvi-tools=0.20.3
  - snakemake-minimal=7.32.4
  - umap-learn=0.5.5
  - scanorama=1.7.4
  - harmonypy=0.0.9
  - python-igraph=0.10.8
  - pip:
      - git+https://github.com/johnarevalo/desc.git
      - git+https://github.com/cytomining/copairs.git@v0.4.0
      - git+https://github.com/johnarevalo/scib.git@frozen_paper
